version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies and Composer..."
      - apt-get update
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php -y || echo "Failed to add PPA, continuing..."
      - apt-get update
      - apt-get install -y php8.4 php8.4-cli php8.4-gmp php8.4-common php8.4-xml php8.4-mbstring || echo "Failed to install PHP 8.4 or GMP"
      - update-alternatives --set php /usr/bin/php8.4 || echo "Failed to set PHP 8.4 as default"
      - echo "extension=gmp" >> /etc/php/8.4/cli/php.ini || echo "Failed to enable GMP extension"
      - php -v  # Debug: Check PHP version
      - php -m | grep gmp  # Debug: Check GMP extension
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version  # Debug: Verify Composer installation

  pre_build:
    commands:
      - echo "Pre-build phase started."
      - ls -la
      - php -v  # Verify PHP version
      - php -m | grep gmp  # Verify GMP extension is loaded
      - php --ini  # Debug: Check loaded PHP configuration files

  build:
    commands:
      - echo "Installing Laravel dependencies..."
      - composer install --no-dev --optimize-autoloader
      - echo "Setting up environment file..."
      - cp .env.example .env
      - php artisan key:generate
      - echo "Caching config and routes..."
      - php artisan config:cache
      - php artisan route:cache
      - echo "Skipping view:cache (API-only app or no Blade templates)."

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
